name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Info
        run: |
              echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
              echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
              echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      - name: Checkout Repo Code
        uses: actions/checkout@v4
      - run: |
              echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
              echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      
      - name: List Repo Files
        run: |
          ls ${{ github.workspace }}

      - name: Build Docker
        run: docker build . --file wargame/Dockerfile --tag wargame-backend:$(date +%s)
  
      - name: CxOne Analyze
        uses: checkmarx/ast-github-action@8e887bb93dacc44e0f5b64ee2b06d5815f89d4fc
        with:
          base_uri: ${{ secrets.CX_BASEURI }}
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          additional_params: --debug --report-format sarif --output-path .

      - name: Upload CxOne Results
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: cx_result.sarif

      - name: Finish
        run: echo "ğŸ This job's status is ${{ job.status }}."